import type { Metadata } from "next";
import Aside from "./Components/aside/Aside";
import "./globals.css";
import RecoilWrapper from "./atoms/RecoilWrapper";
import GlobalComponent from "./Components/modal/GlobalComponent";
import Header from "./Components/Header";
import { getCookie } from "cookies-next";
export const metadata: Metadata = {
  title: "dumpling admin",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative w-screen overflow-x-hidden overflow-y-auto">
        <RecoilWrapper>
          <Header />
          <main className="min-h-[calc(100vh-3rem)] max-h-fit bg-gray-200 flex mx-auto shadow-2xl">
            <Aside />
            <section className="w-[70%] min-w-[calc(100%-200px)] flex items-start justify-center">
              {children}
            </section>
          </main>
          <GlobalComponent />
        </RecoilWrapper>
      </body>
    </html>
  );
}
